image: Visual Studio 2017

environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: "4"
  - nodejs_version: "6"
  - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
